### ISSUE TITLE
Cue/Flac split

### ISSUE THREAD

**Issue by rix1337** [TheCaptain989/lidarr-flac2mp3#12]
Hi, this script works really well for Releases with individual flac files for each track. There are however albums that consist of just one flac and a cue file.

A method to automatically split these into individual tracks would be the perfect addition to this project.

Lidarr has no current method of splitting these, so you might not be able to fix this in your script.

**Comment by TheCaptain989** [comment]
That’s a pretty good idea.  I’ll work on it this week.  Not sure how easy or hard it will be yet.

**Comment by TheCaptain989** [comment]
Okay, this is totally doable with shntool, _but_, and more interestingly, it is also a bit more difficult to do natively with FFMpeg.  Rather than add shntool to the container I'm going to try and script parsing it using FFMpeg alone.

I'm working with one sample FLAC and CUE file that I found.

**Comment by rix1337** [comment]
Alright, thanks for trying! Ill look into Post processing in sabnzbd itself, upon a finished download. 

Might work if the split happened before Lidarr was notified of the completed download.

But yeah,.. this probably needs to be done natively in Lidarr.
