### ISSUE TITLE
Add images for ARM architecture

### ISSUE THREAD

**Issue by patrickjmcd** [TheCaptain989/lidarr-flac2mp3#21]
Currently the dockerhub images are `amd64` only. Using [buildx](https://docs.docker.com/buildx/working-with-buildx/) would allow multi-architecture builds.

For example, I was able to clone this repo and run 

```Shell
docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag patrickjmcd/lidarr:latest --push .
```

to build a multi-arch image

**Comment by TheCaptain989** [comment]
I had multi-architecture on my list.  I’m using the Docker Hub auto build though, so I’m going to have to figure out how to do it that way.  Now that I know it’s needed I’ll spend time to work it out.

**Comment by patrickjmcd** [comment]
Happy to help out if you need it

**Comment by TheCaptain989** [comment]
I’ll take you up on that!  I’m guessing it a change to the hooks build?
Anyway, I can add you to the project if you want to take it.

**Comment by patrickjmcd** [comment]
Sounds great. I've never used hooks before, but I'm happy to learn

**Comment by TheCaptain989** [comment]
I spent a bit of time playing with this, trying to make it work with Docker Cloud builds.  I tried just altering the build hook, but that just generates an error message on DockerHub.  I managed to get something working using GitHub Workflows, but it complicates other things.
I've added you as a contributor.  Maybe you'll have better luck that I did.

**Comment by TheCaptain989** [comment]
@patrickjmcd, please try my latest [Docker Mods](https://github.com/TheCaptain989/lidarr-flac2mp3/tree/TheCaptain989-docker-mod) build [here](https://hub.docker.com/repository/docker/thecaptain989/flac2mp3-mod).  Instead of the `:latest` tag, though, use `:arm64`.  I don't have an ARM system to test this on, but I'm very curious if this works for you.

**Comment by patrickjmcd** [comment]
I'll give this a shot this evening!

**Comment by patrickjmcd** [comment]
I tried running the image on an arm64 machine and got `Error: failed to generate container "fda4b2f1c8cdb035c21dd5b04fe1283e7b46ba2bdcc74a7aaadaaa2cdc7cf3e4" spec:  │
│ no command specified`

**Comment by TheCaptain989** [comment]
Just to tie this one up, I spoke with the guys at Linuxserver.io, and they got me me realize that with their Docker Mods there's no reason to try to build other architectures for simple script mods (which this is).  The base image is multi-arch, and then the mod is dynamically pulled and my script does what is needs on whatever architecture it is running on (x86, Arm, whatever is supported by the base image).
I'm going to rework my Travis CI YAML build script to avoid confusion.
