### ISSUE TITLE
Option to use -v0 instead of CBR

### ISSUE THREAD

**Issue by DjRicko** [TheCaptain989/lidarr-flac2mp3#23]
Would be nice to have the option of using lame -v0 instead of static 320 CBR... Quality ends up the same with alot smaller file size.

**Comment by TheCaptain989** [comment]
Sorry for the delay is replying...email spam filtering

I'll look into this.

**Comment by TheCaptain989** [comment]
Okay, I've got a working test of this.  Updating documentation now and I'll be uploading soon.

**Comment by TheCaptain989** [comment]
Resolved
