### ISSUE TITLE
Conversion seems to increase the size of embedded cover art.

### ISSUE THREAD

**Issue by whi-tw** [TheCaptain989/lidarr-flac2mp3#24]
I've seen some inflation of file sizes during the conversion process. This appears to be because jpgs are being converted to pngs.

when converting manually, I add `-c:v copy` to the ffmpeg commandline, which just copies the jpg over. Searching around to find some kind of reference, this appears to be the solution used here: https://superuser.com/a/1605308

**Comment by whi-tw** [comment]
some data:

```
exiftool Lorde/Pure\ Heroine/08\ -\ Still\ Sane.flac | grep Picture
Picture                         : (Binary data 729115 bytes, use -b option to extract)
exiftool Lorde/Pure\ Heroine/08\ -\ Still\ Sane.mp3 | grep Picture
Picture                         : (Binary data 3725056 bytes, use -b option to extract)
```

**Comment by TheCaptain989** [comment]
Holy ballooning cover art, Batman!  I never noticed this. 🤨
Let me verify this and I'll get back with you.

**Comment by TheCaptain989** [comment]
I have verified this behavior and am implementing the suggested fix.  I'll be publishing an update soon with your other Issue #25 and issue #23

**Comment by whi-tw** [comment]
Amazing! Thanks! I'll take a look in the morning!

**Comment by TheCaptain989** [comment]
Resolved
