### ISSUE TITLE
Converted items have different permissions to original

### ISSUE THREAD

**Issue by whi-tw** [TheCaptain989/lidarr-flac2mp3#25]
My files are all `0664`, but after flac2mp3 runs, they're changed to `0644`.

Is it possible to ensure the resulting mp3 is created with the same permissions and user / group as the original flac?

**Comment by whi-tw** [comment]
I guess the easiest way to do this would be with `chmod --reference=Track NewTrack` before removing the original?

**Comment by TheCaptain989** [comment]
Seems easy enough.  I'll work on this as time permits.

**Comment by TheCaptain989** [comment]
I've got a working test of this and will be uploading soon.

**Comment by TheCaptain989** [comment]
Resolved
