### ISSUE TITLE
[enhancement] additional codecs possible?

### ISSUE THREAD

**Issue by mueslimak3r** [TheCaptain989/lidarr-flac2mp3#27]
Since this project uses ffmpeg would it be possible to convert to Opus instead of mp3, or even other codecs?

Official support for other codecs would be cool but I'm also going to try to modify the scripts to do this on my own. However this will be my first time using docker mods so we'll see how that goes.

If allowing other codecs is something this project is open to then I would be happy to propose a pull request if I get something working.

I'm going to focus on Opus first.

**Comment by TheCaptain989** [comment]
Yes, you're absolutely correct.  Anything ffmpeg is capable of should be possible.  I'm totally unfamiliar with Opus, but I'll get started looking at it this weekend!

Great idea.

**Comment by mueslimak3r** [comment]
Awesome. From my understanding is that using ffmpeg for opus should be very similar to mp3. I've been targeting 192Kb/s for my stereo conversions from FLAC. Based on AB testing on audio forums most people anecdotally say Opus is transparent above 128kb/s, but I wanted to be extra safe.

**The reasons for choosing Opus are that:**
* mp3 is old and has structural design flaws that can result in predictable artifacts. while most people can't hear them, and im certainly not some bit-perfection evangelist, it's a clear detractor for mp3. Opus does not have the same flaws, and while no lossy codec is perfect, it's considered the gold standard for high compression audio.
* Opus can be transparent for simple voice recordings (audiobooks, etc) at 64Kb's, and for most music around 128Kb/s
* By now Opus has wide support in audio playback devices, and near universal support in modern streaming devices
* Because it can be transparent at such low bitrates, using Opus for music storage could remove the need to have transcoding support for a user's media server of choice. In my case that's Jellyfin. A benefit for avoiding transcoding is that the transcoding settings for many music clients is mp3 or AAC at a set bitrate, which isn't very flexible.

Here are some resources:
https://ffmpeg.org/ffmpeg-codecs.html#libopus-1
https://github.com/nicklansley/allav

**Comment by mueslimak3r** [comment]
As detailed in the second resources link in my last comment, to get the full features of the opus encoder from ffmpeg, it has to be built with libopus using the flag `--enable-libopus`

**Comment by TheCaptain989** [comment]
Good news, the default apt-get install already is configured with `--enable-libopus`:

```
ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Hyper fast Audio and Video encoder
```

**Comment by TheCaptain989** [comment]
Okay, first snag.  File conversion work well.... but only if I leave off any embedded images.
I get the following error when I try to use the `-c:v copy -map 0` ffmpeg options on FLAC files with images:
```
[opus @ 0x56516f04ee40] Unsupported codec id in stream 1
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:0 --
```

So, I can convert the audio files, but at the expense of losing covert art.
Still experimenting...

**Comment by mueslimak3r** [comment]
> So, I can convert the audio files, but at the expense of losing covert art.

I can't speak for the bulk of users but I would not want images to be embedded to save on space, and I'd instead rely on the metadata downloaders in lidar, and my media server. This is partially because I like having high resolution images for my music and embedding it for each track in an album would be redundant.

For Opus specifically, it looks like the standard doesn't support images themselves, but it does support base64 data to be embedded, which could be decoded client side. However this likely wouldn't be supported universally

Resources:

https://unix.stackexchange.com/questions/495382/how-do-i-embed-a-jpg-thumbnail-to-a-ogg-opus-audio-file-with-a-script

**Comment by TheCaptain989** [comment]
Okay, that was quick.  I've found I can use `-c:v libtheora -map 0 -q:v 10` options instead to convert and preserve the cover art, at least in VLC.  Going to play with it a bit to be sure this is the correct way to do this.

**Comment by mueslimak3r** [comment]
Perhaps enabling image embedding could be the default but could be explicitly enabled/disabled with a flag like `--image-embed=true/false`

**Comment by TheCaptain989** [comment]
> Perhaps enabling image embedding could be the default but could be explicitly enabled/disabled with a flag like `--image-embed=true/false`

That's a good idea.  More work to do. 😉

**Comment by TheCaptain989** [comment]
Also, I see Opus is closely tied to OGG containers as it is a successor to Vorbis.  Just experimenting, the Opus encoded audio plays fine with either `.ogg` or `.opus` extensions.
Which would suggest as the extension?

**Comment by mueslimak3r** [comment]
"Opus was originally specified for encapsulation in Ogg containers, specified as audio/ogg; codecs=opus, and for Ogg Opus files the .opus filename extension is recommended."

https://en.m.wikipedia.org/wiki/Opus_(audio_format)#Containers

https://en.m.wikipedia.org/wiki/Ogg#Ogg_codecs

**Comment by mueslimak3r** [comment]
Vorbus != Opus though so it's important that they aren't confused. The Opus smart encoder will choose between using the SILK encoder for low bitrate, mostly voice audio, and the CELT encoder for high bitrate content like music. The CELT encoder is basically Vorbus. But the SILK is nothing like Vorbus

**Comment by TheCaptain989** [comment]
Got it.  Thanks.

**Comment by TheCaptain989** [comment]
I just published a new development release v1.3 (b6fc4fb3ee1417d9ef9e7e7f5d46bcadffc28148).
I took the path of making the script accept any valid ffmpeg options, to provide the greatest flexibility.
Just for you, I created a [flac2opus.sh](https://github.com/TheCaptain989/lidarr-flac2mp3/commit/b6fc4fb3ee1417d9ef9e7e7f5d46bcadffc28148#diff-8d0105d0b5ce088f81f8a36f819185ca5e8d0f7c231650846f08180f26868c7a) wrapper script that should do what you want.

Please try it out and let me know what you think.

**Comment by mueslimak3r** [comment]
Absolute legend!! This is so awesome.

Small issue:
the flac2opus.sh script results in "permission denied" inside lidarr when I click "test". The other scripts run fine.

![image](https://user-images.githubusercontent.com/28824542/134785958-c117c212-1ec5-4784-b25b-ec04512ac70d.png)

**Comment by mueslimak3r** [comment]
Here's the log output:

![image](https://user-images.githubusercontent.com/28824542/134786133-caa9b1e1-5b76-4a9c-ac4b-aeb8e0e1d64f.png)

**Comment by mueslimak3r** [comment]
just copying the flac2opus.sh to my /config folder and giving it u+x permissions like any other custom wrapper, and adding it from there works

**Comment by TheCaptain989** [comment]
Doh! 🤦‍♂️
Okay, try the new 09624fd14b3a889a07860ec061f4b8780eca1c9b commit.  One small change in the init script.
I verified it works when I pull it.

**Comment by mueslimak3r** [comment]
Thanks for all your help!

After thorough testing with lidarr, my media server (jellyfin), and some stubborn clients (Gelli, Jellyfin Android, and a couple others), I settled on the snippet that discards video streams (album art), and I made the  bitrate "K" lowercase to be consistent with other examples I've seen. `-vn -c:a libopus -b:a 192k`.

Many of the clients I tried didn't like the video stream with album art and refused to play the tracks unless I skipped forward past the beginning, which I'm guessing forces it to just play the audio stream.

**Comment by TheCaptain989** [comment]
Thanks for the compatibility feedback.  Maybe I'll use your options in my supplied file, then.
I may revisit this later, but for now I'll consider it closed.  I'll try to research a bit more what exactly ffmpeg is doing when I encode an image in a Theora stream, or if there's a more standard way to attach images.

**Comment by mueslimak3r** [comment]
Sounds good. I suspect the issue isn't always just having the photo though. Some tracks play fine with it while others don't, so there's more to it.

I suspect one of the issues is the use of `-map 0` for the artwork snippet since it can result in more than one stream, one in the original format, and one in theora. It's shown below in the Gellu client.

One potential approach if you tackle the issue of handling streams a little more precisely could be analysing the media first to get map indexes, through a tool like `ffinfo`, and then feeding that into the encoding module.

![Screenshot_20210929-012534_Jellyfin](https://user-images.githubusercontent.com/28824542/135307335-79d0e7b5-b19b-4e32-b568-9ed1413c0a22.jpg)

**Comment by TheCaptain989** [comment]
Huh, interesting.  My testing didn't generate any files like this (checked w/Mediainfo) or any unplayable files, but I didn't test nearly as thoroughly as you.  You may be on to something with the `-map 0` command.  Maybe `-map 0:v`?
There's also a documented `-disposition attached_pic` command that I can't get to work at all.
<sigh>  This is one of the reasons I wrote a wrapper for ffmpeg in the first place.  The options are too damn confusing.

**Comment by StormPooper** [comment]
I had to re-encode without the album art for a recent download as Plex struggled with 9/12 of the tracks it converted, completely refusing to apply the metadata to them and struggling to read the media info for most of it.

Tried various searches and my reading online suggests using `opusenc` from `opus-tools` to do the encoding instead if you want to preserve artwork, it's just [not supported properly](https://trac.ffmpeg.org/ticket/4448) in `ffmpeg` and every search I do eventually leads back to that same bug ticket or one about [using some very verbose scripting](https://superuser.com/questions/169151/embed-album-art-in-ogg-through-command-line-in-linux) to use `vorbiscomment` (though the comments suggest it won't work with Opus files).

The other solution I've seen is using `kid3-cli` to tag the file after encoding, though I think you'd need to dump the artwork to a file first.

**Comment by mueslimak3r** [comment]
That's some useful information, thanks! For me, the clients I use will download HD artwork for me. So I avoid embedding artwork in the first place. As long as everything is tagged correctly it's smooth sailing.

As far as using opusenc, I bet you could fork this repo and tweak the build script and the encoder script so it uses that instead of ffmpeg. The linuxserver containers can use any git repo URL for a plugin.
