### ISSUE TITLE
Format option "ALAC"

### ISSUE THREAD

**Issue by Chris230291** [TheCaptain989/lidarr-flac2mp3#28]
Hi. Could you add support for flac2alac please?

`ffmpeg -i input.flac -c:v copy -c:a alac output.m4a`

Is it possible to batch convert like in your Sonarr/Radarr script?

**Comment by TheCaptain989** [comment]
You can code in ALAC support (or any other ffmpeg supported format) by creating a custom wrapper script. I discuss this in the [Syntax](https://github.com/TheCaptain989/lidarr-flac2mp3#syntax) part of the README.

In your case, based on your question above I would create a `/config/flac2alac.sh` file that looks like the following:
```shell
#!/bin/bash

. /usr/local/bin/flac2mp3.sh -a "-c:v copy -c:a alac" -e m4a
```

Let me know how that works out.

To your second point, I have considered a batch mode, but there are file tagging issues that with that approach that aren't easily addressed.  However, let me take a fresh look at this.

**Comment by Chris230291** [comment]
Thanks

**Comment by TheCaptain989** [comment]
> Thanks

@Chris230291, I added the batch mode to this dev repo.  Please test it out.

**Comment by Chris230291** [comment]
Thanks. Unfortunately I have already converted existing tracks using db power amp. By the way he correct command for alac is `. /usr/local/bin/flac2mp3.sh -a "-vn -acodec alac" -e m4a` this stops a lot of errors with album art metadata etc. Its not such a big deal omitting it because Lidarr can just add it back.

**Comment by TheCaptain989** [comment]
Thanks!

**Comment by TheCaptain989** [comment]
Release 2.0 closed this.
