### ISSUE TITLE
VBR wrapper outputs 128 kbit mp3

### ISSUE THREAD

**Issue by DjRicko** [TheCaptain989/lidarr-flac2mp3#29]
The VBR wrapper script seems to suddenly output 128 kbit mp3 instead of -V0 VBR?
Think this started with the additional codec support being added. But can't seem to find where the logic is broken in the code.

**Comment by TheCaptain989** [comment]
Hmmm.  Let me look into that one.

**Comment by TheCaptain989** [comment]
Weird.  It looks like a subtle bug that was there from the beginning; something that was introduced in release 1.3 with commit b6fc4fb.
Fixing it now...

**Comment by TheCaptain989** [comment]
@DjRicko, Please test out the fix using this dev repo and let me know.

**Comment by DjRicko** [comment]
> @DjRicko, Please test out the fix using this dev repo and let me know.

Works perfectly again now, thanks alot for your great work. :)
