### ISSUE TITLE
Options for convert destination path and keep source files

### ISSUE THREAD

**Issue by BDDam** [TheCaptain989/lidarr-flac2mp3#30]
Hi, thank you for this awesome Lidarr docker mod !

Made a custom wrapper for flac2alac as mentioned here on the repo and it's working very well :)

I plan to use this mod in my workflow to keep source `.flac` files intact in the Lidarr-managed library, and just "mirror" imported files in their own ALAC library for iTunes (using its own `Automatically Add to iTunes` folder for import upon next opening, but that's outside the scope here).

One improvement I would love to see to this script is to be able **keep original files** as well as specifying a **different target location** for converted files (ie. `--target` and `--keep` options ?).

Here are the impacts I see with such new options :
- `target` option not set would still default to source directory
- `keep` option not set would still default to current behaviour with Lidarr's Recycle Bin
- if both options are set, I guess Lidarr API scan call can be skipped (?)

What would you think about it ?
Thank you

**Comment by TheCaptain989** [comment]
Hmmmm.  This isn't a bad idea.  I'm leaning to just one option that keeps the original flac and redirects the output target, but let me think on it.

**Comment by TheCaptain989** [comment]
So, after some thought and looking at [GNU standards](https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html), I'm about settled on `--output` and `--keep-file` options, with their functions working as you describe.

I'll start working to incorporate these into my script as time permits.

**Comment by TheCaptain989** [comment]
Okay, I have published an update.  Please pull the `latest` script version from this dev repo and let me know how it works for you.

**Comment by BDDam** [comment]
Awesome, thank you very much!

I pulled the lastest version, ran an album import test and the new options did copy the converted files to specified target while keeping original ones in their folder.

```
22-5-7 02:19:29.9|[3475]Info|Lidarr event: AlbumDownload, Artist: Green Day (11), Album: Â¡Uno! (547), Advanced options: '-c:a alac', File extension: .m4a, Output: /multimedia/Musiques/iTunes/iTunes Media/Ajouter automatiquement Ã  iTunes/, Keep source, Track(s): [...]
22-5-7 02:19:29.9|[3475]Info|Writing: /multimedia/Musiques/iTunes/iTunes Media/Ajouter automatiquement Ã  iTunes/01 - Nuclear Family.m4a
22-5-7 02:19:31.5|[3475]Info|Writing: /multimedia/Musiques/iTunes/iTunes Media/Ajouter automatiquement Ã  iTunes/02 - Stay the Night.m4a
22-5-7 02:19:33.8|[3475]Info|Writing: /multimedia/Musiques/iTunes/iTunes Media/Ajouter automatiquement Ã  iTunes/03 - Carpe Diem.m4a
22-5-7 02:19:35.5|[3475]Info|Writing: /multimedia/Musiques/iTunes/iTunes Media/Ajouter automatiquement Ã  iTunes/04 - Let Yourself Go.m4a
22-5-7 02:19:37.1|[3475]Info|Writing: /multimedia/Musiques/iTunes/iTunes Media/Ajouter automatiquement Ã  iTunes/05 - Kill the DJ.m4a
22-5-7 02:19:38.9|[3475]Info|Writing: /multimedia/Musiques/iTunes/iTunes Media/Ajouter automatiquement Ã  iTunes/06 - Fell for You.m4a
22-5-7 02:19:40.6|[3475]Info|Writing: /multimedia/Musiques/iTunes/iTunes Media/Ajouter automatiquement Ã  iTunes/07 - Loss of Control.m4a
22-5-7 02:19:42.2|[3475]Info|Writing: /multimedia/Musiques/iTunes/iTunes Media/Ajouter automatiquement Ã  iTunes/08 - Troublemaker.m4a
22-5-7 02:19:43.7|[3475]Info|Writing: /multimedia/Musiques/iTunes/iTunes Media/Ajouter automatiquement Ã  iTunes/09 - Angel Blue.m4a
22-5-7 02:19:45.2|[3475]Info|Writing: /multimedia/Musiques/iTunes/iTunes Media/Ajouter automatiquement Ã  iTunes/10 - Sweet 16.m4a
22-5-7 02:19:46.8|[3475]Info|Writing: /multimedia/Musiques/iTunes/iTunes Media/Ajouter automatiquement Ã  iTunes/11 - Rusty James.m4a
22-5-7 02:19:48.9|[3475]Info|Writing: /multimedia/Musiques/iTunes/iTunes Media/Ajouter automatiquement Ã  iTunes/12 - Oh Love.m4a
22-5-7 02:19:51.3|[3475]Info|Original audio file(s) kept, no rescan performed.
22-5-7 02:19:51.3|[3475]Info|Completed in 0m 22s
```

This will be of great use for me :)
Thanks a lot for your work !

**Comment by TheCaptain989** [comment]
Release 2.0 closes this.
