### ISSUE TITLE
Question, not issue: how to update?

### ISSUE THREAD

**Issue by janaxhell** [TheCaptain989/lidarr-flac2mp3#35]
Hi, I've been using your script for a few months. Today I decided to check your github and saw you updated several times.
How do I update it? Or does it update by itself? I'm on Docker and I can see from Portainer if a container as been updated by Watchtower in the Image list on left panel, but flac2mp3 is a script, not a container, so I don't know what version I have.

**Comment by TheCaptain989** [comment]
Docker Mods are updated by the linuxserver.io scripts whenever a container starts.  So, if you're using Watchtower (or even just stopping and starting the container) my script should be updating with the container.

You can check the script version in two ways:
1. Search the Docker container log for a "Version:" string in the section beginning with `>>> Flac2MP3 Mod by TheCaptain989 <<<`.
2. Within the container, execute `/usr/local/bin/flac2mp3.sh --version` from the command line.  You can also do this from the Docker host with a `docker exec <container_name> /usr/local/bin/flac2mp3.sh --version` command.

In either case, you'll see a 7-character hexadecimal string.  This corresponds to the commit hash of a particular build.  The current version for the Development repo is [56c7e28](https://github.com/TheCaptain989/lidarr-flac2mp3/commit/56c7e28fa3de558981f1936347d9366c2de38767) and [2a2faa2](https://github.com/linuxserver/docker-mods/commit/2a2faa23f0a28dffcc4e2b03da6a94f6e7dcb8f1) for Production.

**Comment by janaxhell** [comment]
Thanks, did the command line check, got flac2mp3.sh 56c7e28, so it's perfectly updating. I thought that being a script it needed a separate updating. Great!

**Comment by TheCaptain989** [comment]
Good deal.
