### ISSUE TITLE
How to add cover art to converted opus file?

### ISSUE THREAD

**Issue by woonaval** [TheCaptain989/lidarr-flac2mp3#38]
Hello,

This is not an issue but I didn't know where else I could ask about it.

I used the custom script flac2opus.sh and it works perfectly fine, but I would like it to save the cover art in the file, as it was there for the original .flac. I'm using the default command ". /usr/local/bin/flac2mp3.sh -a "-vn -c:a libopus -b:a 192k" -e .opus"

I checked the syntax, and the options/arguments, but I can't see a clear way to specify this. I blindly tried adding "-map 0" to the command because it felt like this could be the option, but nothing changed.

Could you help me? Thank you!

**Comment by woonaval** [comment]
thanks for the answer! I tried removing the -vn parameter and the converted opus files still don't have the embedded art :( they look the same. For me there is no need to write it to a separate file, I just want to keep the album art inside the file tags as it was in the original .flac file.
thanks again

**Comment by TheCaptain989** [comment]
I knew I had looked at this before!  It's an example in my Readme.

Replace the '-vn' with '-c:v libtheora -map 0 -q:v 10' keeping the other option intact.

Let me know how it goes.

**Comment by woonaval** [comment]
Sadly same result :/

For the record, the full line I'm using now is:
. /usr/local/bin/flac2mp3.sh -a "-c:v libtheora -map 0 -q:v 10 -c:a libopus -b:a 192k" -e .opus

thanks

**Comment by TheCaptain989** [comment]
Stinkola.
There is an old issue (#27) that goes into the weeds a bit about embedding cover art in Opus files. You could read through that and see if you find something useful. It is just not straightforward when using ffmpeg, I'm afraid.
I'm sorry I couldn't help more.

**Comment by woonaval** [comment]
I've read the issue you mention and well my solution is described there! I'm very new to Lidarr, and I wasn't aware that it will parse newly downloaded files to complete its metadata. That is the case, and even if my opus files don't have cover art, after some minutes Lidarr will trigger the metadata update and the art will be there :) so, it's not a real "solution", but works perfectly fine for my needs, as I use flac2mp3 exclusively with Lidarr. Thanks for looking into the topic anyway! appreciated
