### ISSUE TITLE
Feature request: flag to prevent rescan

### ISSUE THREAD

**Issue by realcanadrian** [TheCaptain989/lidarr-flac2mp3#39]
First the obligatory: this is amazing, and I sincerely appreciate all your hard work!

Next the request: It seems Lidarr scan ALL the files every time the script calls for a re-scan, and with tens of thousands of files, it takes quite a long time. As I'm currently rebuilding my library, I have dozens and dozens of re-scans queued up in Lidarr, and it's spending much more time re-scanning already-imported/converted files than importing/converting more. Would it be possible to implement a flag to run the script (and still delete FLAC files after conversion) but _not_ tell Lidarr to scan afterwards? Just to be used until my library is back at steady-state then I could set it back to normal behaviour. For now I've commented out the section of the script that tells the API to scan, but that's not ideal if the container is recreated.

**Comment by TheCaptain989** [comment]
You're welcome!

Tell me about it!  There's a rant somewhere in here about how stupid Lidarr is about a rescan.

I'll consider a switch to disable the scan, but my first choice is to directly tell Lidarr about the new files and skip the rescans entirely. Give me a bit to work through the feasibility of that approach and I'll let you know.

**Comment by TheCaptain989** [comment]
Ugh.  My ultimate solution is going to take some work.

But, to solve your issue, I found something on https://wiki.servarr.com/lidarr/faq 

>A common complaint is the Refresh task causes heavy I/O usage. One setting that can cause issues is "Rescan Artist Folder after Refresh". If your disk I/O usage spikes during a Refresh then you may want to change the Rescan setting to `Manual`. Do not change this to `Never` unless all changes to your library (new releases, upgrades, deletions etc) are done through Lidarr. If you delete release files manually or a third party program, do not set this to `Never`.

I was thinking you could set the "Rescan Artist Folder after Refresh" to `Manual` and see if it helps.

**Comment by TheCaptain989** [comment]
I just created a new branch and uploaded the new script.

I'm still testing myself, but if you are brave, you can pull this new version by setting your DOCKER_MODS variable to `thecaptain989/lidarr-flac2mp3:develop`

**Comment by realcanadrian** [comment]
This is amazing! I'll have to give it a try!

**Comment by TheCaptain989** [comment]
I just pushed another commit to the develop branch.  Have you had a chance to test at all?  I think I'm close unless you encountered any issues.

**Comment by TheCaptain989** [comment]
I pushed several more candidates, but I think I'm done testing unless you have run into anything.

**Comment by realcanadrian** [comment]
I’m sorry I haven’t had a chance to test yet. I’ll try to pull the new
version and give it a whirl. Thanks for all your hard work on this!

**Comment by realcanadrian** [comment]
Installed with `thecaptain989/lidarr-flac2mp3:latest` and it seems good so far... I'll try throwing some stuff at it and see if there are any problems.

**Comment by TheCaptain989** [comment]
> Installed with `thecaptain989/lidarr-flac2mp3:latest` and it seems good so far... I'll try throwing some stuff at it and see if there are any problems.

Great.  I'd love to see some `flac2mp3.txt` log entries if you're willing to share.

**Comment by realcanadrian** [comment]
> Great. I'd love to see some `flac2mp3.txt` log entries if you're willing to share.

https://pastebin.com/xK2k0Gjy

**Comment by TheCaptain989** [comment]
> > Great. I'd love to see some `flac2mp3.txt` log entries if you're willing to share.
> 
> https://pastebin.com/********

Thank you!  Looking through this, I'm a bit concerned.  The first import failed with a curl error and all the others timed out after 1 minute.  You say it appears to be working though?

**Comment by realcanadrian** [comment]
So I'm not sure what's going on with the first one. The tracks don't show in Lidarr but they're present in the folder structure. The rest of them all show in Lidarr and the folder structure. Lidarr in general seems to be kind of sh**ting itself, probably because of

> Artist 5412
> Inactive 1021
> Continuing 4391
> Monitored 1805
> Unmonitored 3607
> Tracks 2485508
> Files 91661
> Total File Size 1.5 TiB

It takes nearly half an hour to scan the disk - even with everything on NVMe - and often goes from "grouping tracks" to "failed" on that task, whatever that means. Sorry, not a developer myself and this is all a bit beyond me.

**Comment by TheCaptain989** [comment]
I found that Lidarr has the same issue as Radarr/Sonarr is that it only allows one import task at a time, so the ManualImport that my script calls gets stuck in 'queued' status until it exits.  I now check for that and exit quickly.
No idea why your Elvis album errored out, but I added extra error info if it ever happens again.

Please stop and start your container to update the script and see if that helps.
