### ISSUE TITLE
[Request] Audio Normalization

### ISSUE THREAD

**Issue by blastbeng** [TheCaptain989/lidarr-flac2mp3#40]
Is it possibile to implement audio normalization using loudnorm in this docker mod?

I mean something like the https://github.com/slhck/ffmpeg-normalize library

It does audio normalization using the native loudnorm ffmpeg filter

Thanks

**Comment by TheCaptain989** [comment]
Hmmm.  Maybe.  Just glancing at the ffmpeg-normalize project makes me think it may be more complex than it seems, but I'll take a look.

**Comment by TheCaptain989** [comment]
After researching this, it sounds like you can do this with my existing script by passing [advanced options](https://github.com/TheCaptain989/lidarr-flac2mp3#command-line-options-and-arguments) to ffmpeg with my scripts `-a` option.  You can create a [custom wrapper script](https://github.com/TheCaptain989/lidarr-flac2mp3/blob/master/README.md#example-wrapper-script) to provide these options.  One example is below.

**Example**
```shell
#!/bin/bash

. /usr/local/bin/flac2mp3.sh -a "-filter:a loudnorm=I=-23:LRA=7 -c:a libmp3lame -b:a 320K" -e .mp3
```

**Comment by TheCaptain989** [comment]
If it does, I'd be happy to add a new custom wrapper for this.

**Comment by TheCaptain989** [comment]
@blastbeng, last call.  If I don't hear anything soon I'm closing this issue.
