### ISSUE TITLE
How to Remove/Uninstall

### ISSUE THREAD

**Issue by Simpuhl** [TheCaptain989/lidarr-flac2mp3#42]
I tried using Portainer by removing the ENV variable and then re-deploying the container, but it just comes right back.

This is an awesome mod but I decided to upgrade all my albums to FLAC instead of converting to MP3.

I couldn't find any removal instructions. Sorry to bother you

**Comment by TheCaptain989** [comment]
No worries.
After you remove the DOCKER_MOD variable, just reset your container and remove the Custom Script configuration in Lidarr.

That a good idea to add this to the README.  I'll leave this open to remind me.

**Comment by Simpuhl** [comment]
> No worries. Not familiar with Portainer. After you remove the `DOCKER_MODS` variable, just reset your container and remove the Custom Script configuration in Lidarr.
> 
> In Synology there is a 'Reset' command to clear the container. From the command line, I think it is `docker system prune --volumes` when the container is stopped.
> 
> That's a good idea to add this to the README. I'll leave this open to remind me.

Hey thank you for the reply, do you mind explaining this a little more:

"remove the Custom Script configuration in Lidarr."

**Comment by TheCaptain989** [comment]
Just click the delete button here:

![lidarr-flac2mp3](../blob/master/.assets/lidarr-custom-script.png?raw=true "Lidarr Custom Script dialog")
