### ISSUE TITLE
lidarr api url building is not correct

### ISSUE THREAD

**Issue by nantostars** [TheCaptain989/lidarr-flac2mp3#44]
Hi,
I'm using this script as docker_mod attached to the lidarr cointainer and I've noticed that in my library flac files weren't deleted after conversion to mp3 anymore (but I don't know when this problem came out).

I've enabled debug and found out that api lidarr url was created with an additional "/" between port and urlbase:

`24-1-14 18:22:30.5|[20104]Debug|Getting Lidarr version. Calling Lidarr API using GET and URL 'http://localhost:8686//lidarr/api/v1/system/status'
24-1-14 18:22:30.5|[20104]Debug|API returned:
24-1-14 18:22:30.5|[20104]Debug|Detected Lidarr version
24-1-14 18:22:30.5|[20104]Debug|Getting track file info for album id 5766. Calling Lidarr API using GET and URL 'http://localhost:8686//lidarr/api/v1/trackFile?albumId=5766'
24-1-14 18:22:30.5|[20104]Debug|API returned:`

The result is that calls to API return nothing and files are not deleted.

This is the current expression for building the url:

`# Build URL to Lidarr API
flac2mp3_api_url="http://$flac2mp3_bindaddress:$flac2mp3_port${flac2mp3_urlbase:+/$flac2mp3_urlbase}/api/v1"`

So I tried to change myself  the url expression removing the "/" after the "+" sign and everything started to work again, but I don't know if it's a fix that works for every case (for example when urlbase is not used).

Anyway please fix this bug and add a docker environment variable to override the url and permitting the user to specify it.

Thanks and congratulations for the excellent work

**Comment by TheCaptain989** [comment]
<sigh>

Sorry about that.  Someone else discovered this bug in my other project as well.  I'll get a development fix out right away.

**Comment by TheCaptain989** [comment]
Please give this a try by changing your DOCKER_MODS variable to:
`DOCKER_MODS=thecaptain989/lidarr-flac2mp3:develop`

**Comment by nantostars** [comment]
I tested with `DOCKER_MODS=thecaptain989/lidarr-flac2mp3:develop` and it works as expected, thanks.
Do you have plan to release this fix in the production version?

**Comment by TheCaptain989** [comment]
Great news!
> Do you have plan to release this fix in the production version?

Yes, I'll submit it to prod very soon.
