### ISSUE TITLE
Cover art integration

### ISSUE THREAD

**Issue by DavidHenryThoreau** [TheCaptain989/lidarr-flac2mp3#46]
Really nice script, do you plan to add cover art integration ?

**Comment by TheCaptain989** [comment]
Thank you.
Can you elaborate? Covert art that Lidarr adds or that is in the FLAC file to begin with is preserved today.

**Comment by DavidHenryThoreau** [comment]
I mean if cover is present on FLAC yes it's preserved in MP3 but if quality is not good, I mean remove and get new album art from MusicBrainz.

**Comment by TheCaptain989** [comment]
Early versions of the script _did_ deal with cover art (look at closed issues #5, #8, and #13).  However, Lidarr itself is supposed to do this, and I don't want to duplicate functionality.

**Comment by DavidHenryThoreau** [comment]
Is supposed yes but I don't think at the moment that's is possible
I've also opened a ticket which is closed..
https://github.com/Lidarr/Lidarr/issues/4174

**Comment by TheCaptain989** [comment]
Observationally, I've seen Lidarr add cover art from MusicBrainz.  It seems like you're wanting more control with beets specifically (which I'm not familiar with).
...
beets looks like it already has a whole plugin ecosystem of its own, including handling cover art (with fetchart and embedart).
Maybe you're better off writing a simple wrapper script in Lidarr for beets?

**Comment by DavidHenryThoreau** [comment]
The best way should be front-end interface to add or remove cover art.

**Comment by TheCaptain989** [comment]
Yeah, Lidarr doesn't lend itself to custom front-ends; I wouldn't even know where to start.  That, and I'm no UI developer; the basic stuff I'm made in the past is God-awful and you would hate it. 😳

Sorry, I'm not your guy.

**Comment by DavidHenryThoreau** [comment]
Yes that's the point, there is not custom from-ends.
Thanks for help !
