### ISSUE TITLE
Converts only first 4 tracks

### ISSUE THREAD

**Issue by Zuluuk** [TheCaptain989/lidarr-flac2mp3#47]
Hi @TheCaptain989
I managed to get this script working, as I didn't need to save the flac files.

However this only convert the first 4 tracks and left everthing else as flac. If you need any logs please let me know.

**Comment by TheCaptain989** [comment]
Yes, I would need your logs, preferably with debug enabled on the script (let's start with level 1).
This is not typical behavior.

**Comment by Zuluuk** [comment]
[flac2mp3.txt](https://github.com/TheCaptain989/lidarr-flac2mp3/files/15235056/flac2mp3.txt)
![covert 3](https://github.com/TheCaptain989/lidarr-flac2mp3/assets/159487901/69500831-8104-4ba9-920d-ab1a1546837c)
Please find the file attatched.

**Comment by TheCaptain989** [comment]
Thank you.

Your log is a mess.  There are a lot of errors I've never seen before.  First, it doesn't even look like it came from a current version of the script. It's also missing the basic stuff I've had in there for many versions, like process ID.
Second, at least at one point you had the a wrong trigger configured in Lidarr.  Please make sure you only have **On Release Import** and **On Upgrade** checked in the Connection configuration (see below).
![image](https://github.com/TheCaptain989/lidarr-flac2mp3/assets/11523885/8279c15f-5317-486a-a382-f53547f65a8a)

Then, please follow the steps below to help troubleshoot further.

### Steps to troubleshoot
1. Please check that you're using the current version of my script  (Raw link [here](https://raw.githubusercontent.com/linuxserver/docker-mods/lidarr-flac2mp3/root/usr/local/bin/flac2mp3.sh)).
2. Execute a `flac2mp3.sh --version` from the command line and report back what the output is.

**Comment by Zuluuk** [comment]
The issue is i followed an older guide and it was pulling the an older script. I reconfigured the docker and redownloaded your latest version it is working fine ty.

**Comment by TheCaptain989** [comment]
Good to hear.  I'm closing.
