### ISSUE TITLE
output file just dumps all the transcoded files in the same dir

### ISSUE THREAD

**Issue by zombiehoffa** [TheCaptain989/lidarr-flac2mp3#50]
Is there a way to make this maintain the same directory structure as lidarr? I don't want to overwrite my flacs but I would like to keep my transcodes in the same directory structure (basedir/artist/album) just with a different base dir from the flacs. I don't need the transcodes to be imported into lidarr or anything, it's fine to just track the flacs there.

**Comment by TheCaptain989** [comment]
I haven't tested this, but you should be able to accomplish this by combining the `--keep` and `--output` [options](https://github.com/TheCaptain989/lidarr-flac2mp3#command-line-syntax) and using [Lidarr environment variables](https://wiki.servarr.com/lidarr/custom-scripts).

You'll have to create a custom [wrapper script](https://github.com/TheCaptain989/lidarr-flac2mp3#wrapper-scripts) that looks something like this:

```shell
#!/bin/bash

album_path="${lidarr_addedtrackpaths%%|*}"

. /usr/local/bin/flac2mp3.sh --keep --output "${album_path%/*}/MP3/"
```

***Please test this!***

**Comment by TheCaptain989** [comment]
I just realized that this is not what you wanted.  The "basedir" idea is harder to accomplish, but not impossible.  Let me think on it for a bit.

**Comment by TheCaptain989** [comment]
Okay, I came up with this, but you'll have to edit the `org_basedir` and `new_basedir` variables to what you want.  *Make sure that both either have or do not have a trailing backslash!*  Again, this is untested.

Here, you have to manually specify the old base because there's no easy way to extract that info from Lidarr.

```shell
#!/bin/bash

# Leave these alone
album_path="${lidarr_addedtrackpaths%%|*}"
album_path="${album_path%/*}"

# Change these two variables to suit your needs
org_basedir=/media/music
new_basedir=/media/MP3

. /usr/local/bin/flac2mp3.sh --keep --output "${album_path#/$org_basedir/$new_basedir}"
```

***Please test this!***

**Comment by zombiehoffa** [comment]
Sorry, my kids distracted me. After your first hint in the right direction I sett his in my docker compose and called flac2mp3 directly so it would use flac2mp3_args:

FLAC2MP3_ARGS: -r '[.][^.]*$' -k -o "/opus/$${lidarr_artist_name/}/$${lidarr_album_title/}" -a "-vn -c:a libopus -b:a 192k" -e .opus

It's ugly but it mostly seems to work. I'm missing the year on the album directory name and that's about it

**Comment by TheCaptain989** [comment]
Yeah, that should work too.  You just won't necessarily have identical artist/album paths.

**Comment by zombiehoffa** [comment]
so the unexpected other issue I am getting is in trying to do the inital bulk transcode it doens't respect any of the above stuff because bath mode seems to turn off any talking to lidarr. Any suggestion on how I would make the above execute as if I had just imported my whole library to lidarr and it constructed the whole alternate opus path?

**Comment by TheCaptain989** [comment]
Sure, you could do something like this:

```shell
find /music/ -type f -name "*.flac" | while read file; do album_stub=${file#/*/*/*}; /usr/local/bin/flac2mp3.sh -f "$file" -r '[.][^.]*$' -k -o "/opus/${album_stub%/*}" -a "-vn -c:a libopus -b:a 192k" -e .opus; done
```

**Comment by zombiehoffa** [comment]
I have no idea what I'm doing with this but with your example above I was getting albums in the /opus dir, what finally worked was:

 find /music/ -type f -name "*.flac" | while read file; do  artname=${file#/*/*}; /usr/local/bin/flac2mp3.sh -f "$file" -r '[.][^.]*$' -k -o "/opus/${artname%/*}" -a "-vn -c:a libopus -b:a 192k" -e .opus; done

variable was changed to artname not because it was a good idea but because this monkey bashing on his keyboart intiitally tried adding a second variable to get the artist name and when that failed spectacuarly tried two stars instead of 3 to see if that gave me what I needed and then kept that..

**Comment by TheCaptain989** [comment]
Yeah, bash parameter expansion and globing can be tricky.  I was making some assumptions with my example.

Anyway, I'm glad you got it to do what you wanted!

**Comment by TheCaptain989** [comment]
Very good news!  Glad you could get it working for you.
