### ISSUE TITLE
Pass additional argument

### ISSUE THREAD

**Issue by blastbeng** [TheCaptain989/lidarr-flac2mp3#51]
Hello,
i'd like to pass additional bitrate argument like -b 256k, since i want to always convert to 256

but on Lidarr i can just modify the path, if i try to add arguments it says "File does not exist"

How can i modify the configuration to always convert to 256k?

I am using lidarr under docker.

Thanks

**Comment by TheCaptain989** [comment]
Yeah, Lidarr removed a GUI way to add command-line arguments to custom scripts some time ago.

I cover this in my [documentation](https://github.com/TheCaptain989/lidarr-flac2mp3#wrapper-scripts), but to summarize, you either must create a custom wrapper script or add arguments to the `FLAC2MP3_ARGS` variable in your Docker configuration.

If you choose a script, I would create it in an externally mapped volume, such as `/config` so it survives container updates.

**Comment by blastbeng** [comment]
Thanks! I have added the env var to my docker container and works like a charm.
