### ISSUE TITLE
Gracefully deal with EventType of Test

### ISSUE THREAD

**Issue by TheCaptain989** [TheCaptain989/lidarr-flac2mp3#9]
This EventType was added in Lidarr v0.7.0.1347

**Comment by tscibilia** [comment]
Is this regarding the error I get when trying to save the custom script path in Lidarr?
I keep getting `Script exited with code: 1`

**Comment by TheCaptain989** [comment]
It could be.  What version of Lidarr are you running?
Also, you are using Linux OS with Docker?

**Comment by tscibilia** [comment]
Oh sorry, I'm running Docker 19.03.2 in a Ubuntu 18.04.3 VM on a proxmox server.
Lidarr v0.7.1.1381

**Comment by TheCaptain989** [comment]
I’ve never tried that exact configuration, but more than likely something changed in Lidarr.  I’ll take a look as time permits tomorrow.

**Comment by TheCaptain989** [comment]
I confirmed it is the version of Lidarr.  I’ll fix the script and rebuild the container today.

**Comment by TheCaptain989** [comment]
Tested and committed.

**Comment by tscibilia** [comment]
Sweet it worked! 
Thanks!
